apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-demo-vpa
spec:
  targetRef:
    apiVersion: v1
    kind: Pod
    name: vpa-demo-app
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
    - containerName: vpa-demo
      controlledResources:
      - memory
      - cpu
      minAllowed:
        memory: "64Mi"
        cpu: "50m"
      maxAllowed:
        memory: "2Gi"
        cpu: "1000m"
